apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflowop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: workflowop
  template:
    metadata:
      labels:
        name: workflowop
    spec:
      serviceAccountName: workflowop
      containers:
        - name: workflowop
          image: REPLACE_IMAGE
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - workflowop
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "workflowop"
